<?php

/**
 * @file
 * Implementation of the Kumquat Core module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\kumquat_core\Helpers\PatternsHelper;
use Drupal\kumquat_core\Plugin\Field\FieldFormatter\TextTrimmedFormatter;

/**
 * Implements hook_element_info_alter().
 */
function kumquat_core_element_info_alter(array &$info) {
  if (!empty($info['pattern'])) {
    $info['pattern']['#pre_render'][] = [
      PatternsHelper::class,
      'handleOptionalFields',
    ];
    $info['pattern']['#pre_render'][] = [
      PatternsHelper::class,
      'handleMultipleFields',
    ];
    $info['pattern']['#pre_render'][] = [
      PatternsHelper::class,
      'handleBooleanFields',
    ];
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function kumquat_core_field_formatter_info_alter(array &$info) {
  $info['text_trimmed']['class'] = TextTrimmedFormatter::class;
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function kumquat_core_locale_translation_projects_alter(&$projects) {
  $modulePath = \Drupal::moduleHandler()->getModule('kumquat_core')->getPath();
  $projects['kumquat_core'] = [
    'info' => [
      'interface translation server pattern' => $modulePath . '/translations/%project.%language.po',
    ],
  ];
}

/**
 * Implements hook_views_data().
 */
function kumquat_core_views_data() {
  $data = [];
  $data['views']['kumquat_facets'] = [
    'title' => t('Facets'),
    'help' => t('Shows facets.'),
    'area' => [
      'id' => 'kumquat_facets',
    ],
  ];
  $data['views']['kumquat_facets_summary'] = [
    'title' => t('Facets summary'),
    'help' => t('Shows facets summary.'),
    'area' => [
      'id' => 'kumquat_facets_summary',
    ],
  ];
  $data['views']['kumquat_result'] = [
    'title' => t('Wrapped result summary'),
    'help' => t('Shows result summary, for example the items per page wrapped in some markup.'),
    'area' => [
      'id' => 'kumquat_result',
    ],
  ];
  return $data;
}

/**
 * @addtogroup Kumquat Gin hook calls
 * @{
 */

/**
 * Implements hook_paragraphs_widget_actions_alter().
 */
function kumquat_core_paragraphs_widget_actions_alter(array &$widget_actions, array &$context) {
  \Drupal::theme()->alter('paragraphs_widget_actions', $widget_actions, $context);
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function kumquat_core_field_widget_complete_form_alter(&$field_widget_complete_form, FormStateInterface $form_state, $context) {
  \Drupal::theme()->alter('field_widget_complete_form', $field_widget_complete_form, $form_state, $context);
}

/**
 * @} End of "Kumquat Gin hook calls".
 */
